# Generated by Django 5.0.4 on 2024-05-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="заголовок")),
                ("sleg", models.CharField(max_length=50, verbose_name="df")),
                ("description", models.TextField(verbose_name="содержимое")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="image/",
                        verbose_name="изображение",
                    ),
                ),
                ("created_at", models.DateField(verbose_name="дата создания")),
                ("publication", models.BooleanField()),
                ("caunt_views", models.IntegerField(verbose_name="просмотры")),
            ],
            options={
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
                "ordering": ("name",),
            },
        ),
    ]
