# Generated by Django 4.2.2 on 2024-06-26 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_options_product_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name_product",),
                "permissions": [
                    ("can_set_published", "can change published status"),
                    ("can_change_product_description", "can change description"),
                    ("can_change_product_category", "can change category"),
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
